service: cmr-cms

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  cognitoPool: ${opt:cognitopool}

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 59
  environment:
    host: ${opt:host}
    pass: ${opt:pass}
    user: ${opt:user}
  vpc:
    securityGroupIds:
      - ${opt:securitygroup}
    subnetIds:
      - ${opt:subnetid1}
      - ${opt:subnetid2}
      - ${opt:subnetid3}

functions:
  pageGet:
    handler: scripts/lambda/page.httpGET
    events:
      - http:
          path: /path/{slug+}
          method: get

  pagePOST:
    handler: scripts/lambda/page.httpPOST
    events:
      - http:
          path: /page
          method: post
          authorizer:
            arn: ${self:custom.cognitoPool}
  pagePUT:
    handler: scripts/lambda/page.httpPUT
    events:
      - http:
          path: /page/{pageId}
          method: put
          authorizer:
            arn: ${self:custom.cognitoPool}

  noticePOST:
    handler: scripts/lambda/notice.httpPOST
    events:
      - http:
          path: /notice
          method: post
          authorizer:
            arn: ${self:custom.cognitoPool}
  noticePUT:
    handler: scripts/lambda/notice.httpPUT
    events:
      - http:
          path: /notice/{noticeId}
          method: put
          authorizer:
            arn: ${self:custom.cognitoPool}
