service: cmr-cms

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-plugin-include-dependencies
package:
  individually: true

custom:
  cognitoPool: ${opt:cognitopool}

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  environment:
    host: ${opt:host}
    pass: ${opt:pass}
    user: ${opt:user}
  vpc:
    securityGroupIds:
      - ${opt:securitygroup}
    subnetIds:
      - ${opt:subnetid1}
      - ${opt:subnetid2}
      - ${opt:subnetid3}

functions:
  pageGet:
    handler: scripts/lambda/page.httpGET
    events:
      - http:
          path: /path/{slug+}
          method: get
          cors: true
  pagesGet:
    handler: scripts/lambda/page.httpGETALL
    events:
      - http:
          path: /path
          method: get
          cors: true

  pagePOST:
    handler: scripts/lambda/page.httpPOST
    events:
      - http:
          path: /page
          method: post
          cors: true
          authorizer:
            type: AWS_IAM
  pagePUT:
    handler: scripts/lambda/page.httpPUT
    events:
      - http:
          path: /page/{pageId}
          method: put
          cors: true
          authorizer:
            type: AWS_IAM
  pageDELETE:
    handler: scripts/lambda/page.httpDELETE
    events:
      - http:
          path: /page/{pageId}
          method: delete
          cors: true
          authorizer:
            type: AWS_IAM

  noticePOST:
    handler: scripts/lambda/notice.httpPOST
    events:
      - http:
          path: /notice
          method: post
          cors: true
          authorizer:
            type: AWS_IAM
  noticePUT:
    handler: scripts/lambda/notice.httpPUT
    events:
      - http:
          path: /notice/{noticeId}
          method: put
          cors: true
          authorizer:
            type: AWS_IAM
